# -*- coding: utf-8 -*-
"""221071047_pandas_numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1alqw4e89O3QgVKpcS2fXiNxPF0YXuiMb
"""

import numpy as np

arr0 = np.array([5,6])

print("Sum of elements of array is: ")
print(sum(arr0))
arr1 = np.reshape(arr0, (2,1))
print((arr1))
arr2 = np.transpose(arr1)
print(arr2)

arr3 = np.array([[1,0,0],[0,1,0],[0,0,1]])
print("Determinant of the above matrix is:")
det = np.linalg.det(arr3)
print(det)
print("The shape of the matrix is:")
print(arr3.shape)

arr4 = np.array([25,60,1,67,89,100,58,77])
arr5 = np.sort(arr4)
print("The sorted array is:",arr5)
print("Smalles element in the array is: ", arr5[0])

from google.colab import drive
drive.mount('/content/drive')
import pandas as pd


df = pd.read_csv("/content/drive/MyDrive/data.csv")
print(df.head())

print(df)

df1 = pd.read_csv('/content/drive/MyDrive/data.csv', skiprows = [1,2])
print(df1)

df.mean(axis = 0)

df.mean(axis = 1)

new_row = {'Duration': '7', 'Pulse': '7', 'Maxpulse':'7', 'Calories': '7'}
df.loc[len(df)] = new_row
df = df.append(new_row , ignore_index=True)

print(df)

cell = df.iloc[169]['Duration']
print(cell)
cell1 = df.iloc[0]['Duration']
print(cell1)

df= pd.read_csv('/content/drive/MyDrive/data.csv')
df.drop('Duration',axis=1,inplace=True)
print(df)