# -*- coding: utf-8 -*-
"""pillow_221071047.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lkF1kJH6FnilZUCagEmHuvugQzphGtpv
"""

from google.colab import files
uploaded = files.upload()

!pip install pillow

from PIL import Image

img = Image.open(r"test_image.jpeg")
display(img)

print(img.mode)

print(img.size)
print(img.format)

angle = 50
img.rotate(angle)
#diplay(img)

angle=90
img1=img.rotate(angle)
size=(300,300)
img1.resize(size)

# img.rotate(0)

# size=(300,300)
# img1 = img.resize(size)
# display(img1)

vertical_img = img.transpose(Image.FLIP_TOP_BOTTOM)
display(vertical_img)

r_img=img.rotate(45, expand=True)
display(r_img)

img.getbands()
img_gray = img.convert("L")
display(img_gray)
img_gray.getbands()
# img.convert("L")
# img.getbands()

cropped_img = img.crop((20,20,100,100))
display(cropped_img)

red, green, blue = img.split()

display(red, green, blue)

red.mode
blue.mode
green.mode

img_merge = Image.merge("RGB", (red,red,blue))
display(img_merge)

from PIL import ImageFilter
blur_img = img.filter(filter = ImageFilter.BLUR)
display(blur_img)

import numpy as np
a = np.asarray(img)
print(a)
print(a.shape)

from PIL import ImageDraw
draw=ImageDraw.Draw(img)
draw.text((20,100),'dell')
display(img)

img.thumbnail((60,60))
display(img)