# -*- coding: utf-8 -*-
"""221071047_(matplotlib)expt9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q5HV5aQJl-PqqeQsC2m4z7AR9wkYnKeF
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from datetime import datetime

data = pd.read_csv('/content/HistoricalPrices.csv')
data.head()

data['Date'] = pd.to_datetime(data['Date'])
data = data.sort_values(by = 'Date')

plt.plot(data['Date'], data[' Close'])
plt.show()

plt.plot(data['Date'], data[' Open'], label = 'Open')
plt.plot(data['Date'], data[' Close'], label = 'Close')
plt.legend()
plt.show()

plt.scatter(data[' Open'], data[' Close'])
plt.show()

data['Date'] = pd.to_datetime(data['Date'])
data = data.sort_values(by='Date')

data['Month'] = data['Date'].dt.month_name()

average_close_by_month = data.groupby('Month')[' Close'].mean()
plt.bar(average_close_by_month.index, average_close_by_month)
plt.xlabel('Month')
plt.ylabel('Average Close Price')
plt.title('Average Close Price by Month')
plt.show()

data['Date'] = pd.to_datetime(data['Date'])
data = data.sort_values(by='Date')

# Plot histogram of 'Close' prices
plt.hist(data[' Close'], bins=20, color='blue', alpha=0.7)
plt.xlabel('Close Price')
plt.ylabel('Frequency')
plt.title('Histogram of Close Prices')
plt.show()

